openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/danubetech/credential-verifier/0.0.2
info:
  description: This is an experimental open API specification for verifying digital credentials based on standards such as the Verifiable Credentials Data Model (https://www.w3.org/TR/vc-data-model/), JWT (https://tools.ietf.org/html/rfc7519), and Open Badges (https://openbadges.org/). Implementations are expected to change significantly and implementers that are not directly involved in the work are strongly urged to not implement this API. Implementations of this API may differ in terms of which data formats or proof formats they do or do not support. Implementations may choose to not support certain parts of this API (e.g. optional parts include retrieving a verification status that has already been created).
  version: "0.0.2"
  title: Credential Verifier API
  contact:
    email: markus@danubetech.com
  license:
    name: All documents in this Repository are licensed by contributors under the [W3C Software and Document License](http://www.w3.org/Consortium/Legal/copyright-software).
tags:
  - name: internal
    description: Internal APIs facing the Verifier.
paths:
  /verifications:
    post:
      tags:
        - internal
      summary: Verify a given credential.
      operationId: verifyCredential
      description: Performs a series of verification checks on a provided Verifiable Credential and returns the overall status of the checks as well as the status of each individual check. Support of this part of the API is REQUIRED for implementations.
      requestBody:
        content:
          application/json:
            schema:
              description: The credential to be verified and a set of options to use when verifying the credential.
              type: object
              properties:
                verifiableCredential:
                  type: object
                  additionalProperties: false
                  description: The verifiable credential to check.
                  example: {
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.edu/credentials/3732",
  "type": [
    "VerifiableCredential",
    "UniversityDegreeCredential"
  ],
  "issuer": "did:example:c6f1c276e12ec21ebfeb1f712eb",
  "issuanceDate": "2020-03-11",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  },
  "proof": [{
    "type": "Ed25519Signature2018",
    "created": "2020-03-11T23:09:06.803Z",
    "jws": "eyJhbGciOiJFZERTQSIsImI2..hS5SPmWTFocjcDg",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:example:c6f1c276e12ec21ebfeb1f712eb#jf893k"
  }]
}
                options:
                  type: object
                  additionalProperties: false
                  description: Options for specifying how the credential will be issued.
                  properties:
                    checks:
                      type: array
                      items:
                        type: string
                      description: An array of verification checks to be performed on the credential. WARNING - Implementers are cautioned that the list of checks is currently incomplete and other checks such as issuance, expiration, nonce, domain, and acceptable issuers are expected to be added in time. A default list is also expected to encapsulate all available checks. This option might be changed to a 'ignore' option where it lists the checks the developer would like to skip.
                      example: ["proof"]
      responses:
        '200':
          description: The verification was successful.
          content:
            application/json:
              schema:
                type: object
                description: A description of the checks that were performed.
                properties:
                  checks:
                    type: array
                    items:
                      type: string
                    description: An array of verification checks that were performed. WARNING - Implementers are cautioned that the list of checks is currently incomplete and other checks such as issuance, expiration, nonce, domain, and acceptable issuers are expected to be added in time.
                    example: ["proof"]
        '400':
          description: The verification failed.
          content:
            application/json:
              schema:
                type: object
                description: A description of the checks that were performed and any associated errors.
                properties:
                  checks:
                    type: array
                    items:
                      type: object
                    description: An array of verification checks that were performed and any associated errors and other information that may be helpful when debugging the failure. WARNING - Implementers are cautioned that the list of checks is currently incomplete and other checks such as issuance, expiration, nonce, domain, and acceptable issuers are expected to be added in time.
                    example: [{
                      "check": "proof",
                      "error": "The verificationMethod (public key) associated with the digital signature could not be retrieved due to a network error.",
                      "verificationMethod": "did:example:c6f1c276e12ec21ebfeb1f712eb#jf893k",
                    }]
    put:
      tags:
        - internal
      summary: Verifies a credential and returns its verification status.
      operationId: verifyCredentialReference
      description: Verifies a credential and returns its verification status. Support of this part of the API is OPTIONAL for implementations.
      requestBody:
        content:
          application/json:
            schema:
              type: object
        description: The credential to be verified.
      responses:
        '201':
          description: verification status successfully created!
          content:
            application/json:
              schema:
                type: object
                description: The credential's verification status. This SHOULD include a reference or ID that can be used later for other parts of the API, e.g. retrieving a verification status that has already been created.
        '400':
          description: invalid input!
        '500':
          description: error!
  /verifications/{verificationReference}:
    get:
      tags:
        - internal
      summary: Retrieves a verification status that has already been created, and returns it in the response body.
      operationId: retrieveVerification
      description: Retrieves a verification status that has already been created, and returns it in the response body. The retrieved verification status MUST be identical to the original verification status when it was first created. Support of this part of the API is OPTIONAL for implementations.
      parameters:
        - in: path
          required: true
          name: verificationReference
          schema:
            type: string
          description: Reference to a verification status that has been created.
      responses:
        '200':
          description: verification status successfully retrieved!
          content:
            application/json:
              schema:
                type: object
                description: The retrieved verification status.
        '400':
          description: invalid input!
        '404':
          description: verification status not found!
        '500':
          description: error!
        '501':
          description: not supported by this implementation!
