title: Workflow
type: object
properties:
  instance:
    type: array
    items: 
      type: string
  definition:
    type: array
    items: 
      type: string
example:
  {
    "@context": ["https://w3id.org/traceability/v1"],
    "type": ["Workflow"],
    "workflow":
      {
        "instance": ["urn:uuid:f5fb6ce4-b0b1-41b8-89b0-331ni58b7ee0"],
        "definition": ["https://w3id.org/traceability#us-cbp-entry"],
      },
  }
