openapi: 3.0.0
info:
  title: Issuer Service
  version: "0.0.3-unstable"
  tags:
    - name: Issuer Service
      description: APIs for issuing and revoking credentials

paths:
  /credentials/issue:
    post:
      tags:
        - Issuer Service
      summary: Issues a credential and returns it in the response body.
      operationId: issueCredential
      description: Issues a credential and returns it in the response body.
      requestBody:
        description: Parameters for issuing the credential.
        content:
          application/json:
            schema:
              type: object
              properties:
                credential:
                  $ref: "./components/Credential.yml"
                options:
                  $ref: "./components/IssuanceOptions.yml"
      responses:
        "201":
          description: Credential successfully issued!
          content:
            application/json:
              schema:
                $ref: "./components/VerifiableCredential.yml"
        "400":
          description: invalid input!
        "500":
          description: error!

  /credentials/revocation-list/{revocation-list-file}:
    get:
      tags:
        - Issuer Service
      summary: Get Revocation List
      operationId: getRevocationList
      description: Get a verifiable credential revocation list
      responses:
        "200":
          description: Revocation List Verifiable Credential
          content:
            application/json:
              schema:
                $ref: "./components/RevocationListVerifiableCredential.yml"
        "400":
          description: Client Error
        "500":
          description: Server Error
  /credentials/status:
    post:
      tags:
        - Issuer Service
      summary: Updates the status of an issued credential
      operationId: updateCredentialStatus
      description: Updates the status of an issued credential.
      requestBody:
        description: Parameters for updating the status of the issued credential.
        content:
          application/json:
            schema:
              type: object
              description: Request for updating the status of an issued credential.
              properties:
                credentialId:
                  type: string
                credentialStatus:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
              example:
                {
                  "credentialId": "urn:uuid:45a44711-e457-4fa8-9b89-69fe0287c86a",
                  "credentialStatus":
                    [{ "type": "RevocationList2020Status", "status": "0" }],
                }
      responses:
        "200":
          description: Credential status successfully updated
        "400":
          description: Bad Request
        "404":
          description: Credential not found
        "500":
          description: Internal Server Error
